### ISSUE TITLE
Demo tracking issue

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#2]
Manual Testnet Demo

- [x] create wallet receive address
- [x] send bitcoin to wallet (from external faucet)
- [x] sync wallet via electrum
- [x] verify received balance
- [x] #4
- [x] #5
- [x] #7
- [x] #8
