### ISSUE TITLE
Remove Alpha3Error

### ISSUE THREAD

**Issue by reez** [bitcoindevkit/bdk-ffi#495]
**Describe the enhancement**  

Just creating a tracking Issue for removing the Alpha3Error, which will mean that we have implemented specific error types for everything needed in `bdk-ffi`

**Additional context**
I currently have a few open draft PR's on this so thought it was a good idea to have a tracking Issue

**TODO**
- [x] format
- [x] alphabetize?
- [x] re-order UDL & error.rs
- [x] tests
- [x] update UDL with proper section headings for some of these (for example, under keys mnemonic from_string/entropy & pathconstructor should not be under descriptor module in UDL)
- [x] naming of error strings (e/err/error/error_message)
- [ ] For the “from”s should we type alias to bdkXYZError or should we be fully explicit like bdk::bitcoin::psbt::ExtractTxError?
- [ ] For this error should we do `use thiserror::Error;`
